"use client";

import Link from "next/link";
import { Scale, AlertTriangle, Shield, Users, FileText, Lock, RefreshCw, Gavel, Coins, Timer, Ban, AlertCircle } from "lucide-react";

export default function TermsPage() {
    const sections = [
        {
            icon: FileText,
            title: "1. Definitions and Scope of Service",
            content: "Ticko provides a social educational platform for financial discussion, simulated stock trading ('Paper Trading'), and AI-driven information tools. The platform is intended for private use, learning, and information exchange."
        },
        {
            icon: Coins,
            title: "2. Virtual Currency and Points",
            highlight: true,
            content: null,
            subsections: [
                { label: "Ticko Dollars", text: "The virtual balance ('$10,000') provided in Paper Trading is simulated funds with absolutely no monetary value." },
                { label: "XP and Levels", text: "Experience Points (XP), Levels, Badges, and other gamification elements are virtual points for entertainment and engagement." },
                { label: "No Currency Exchange", text: "Virtual funds, XP, and Levels can never be exchanged for real money, credits, goods, or services. Attempting to sell or transfer virtual assets is strictly prohibited." }
            ]
        },
        {
            icon: Timer,
            title: "3. Fair Play and Lock-in Rule",
            content: "To ensure fair competition and prevent 'arbitrage cheating' due to delayed market data, the following applies:",
            list: [
                "Market data may be delayed by up to 15 minutes.",
                "After a purchase in Paper Trading, the position is locked for 30 minutes before selling is possible.",
                "This rule exists to prevent exploitation of data delays and guarantee fair competition."
            ],
            footer: "Ticko reserves the right to adjust lock-in times and Fair Play rules to maintain platform integrity."
        },
        {
            icon: AlertTriangle,
            title: "4. No Financial Advice",
            highlight: true,
            content: null,
            subsections: [
                { label: "General Information", text: "All content on Ticko, including but not limited to texts, charts, sentiment data, and answers generated by Ticko AI, shall be considered general information." },
                { label: "Not Advice", text: "No content constitutes financial advice, investment recommendations, tax advice, or legal advice." },
                { label: "AI Limitations", text: "Ticko AI is based on machine learning models that can generate incorrect, incomplete, or outdated information. Ticko does not guarantee the accuracy of AI-generated analyses." }
            ]
        },
        {
            icon: Ban,
            title: "5. Market Abuse and Manipulation",
            highlight: true,
            content: "Ticko does not tolerate attempts at improper market influence:",
            list: [
                "Pumping/Dumping: Systematic attempts to manipulate sentiment around individual stocks to mislead other users.",
                "Coordinated Campaigns: Organized dissemination of misleading information.",
                "Fake Wins: Manipulation of own results through technical methods."
            ],
            footer: "Users violating these rules will be suspended permanently without warning. Ticko cooperates with authorities upon suspicion of actual market abuse."
        },
        {
            icon: AlertCircle,
            title: "6. Disclaimer of Liability",
            content: null,
            subsections: [
                { label: "Own Decisions", text: "Ticko is not responsible for financial losses incurred if a user chooses to copy trades from the platform in real life with external brokers." },
                { label: "Third Party Data", text: "Market data is retrieved from external providers. We do not guarantee that this data is correct, complete, or delivered in real time." },
                { label: "Technical Interruptions", text: "The service is provided 'as is'. Ticko is not responsible for direct or indirect damages resulting from technical errors or delayed data." }
            ],
            footer: "All trading with real money happens at the user's own risk with external, licensed brokers."
        },
        {
            icon: RefreshCw,
            title: "7. Reset and Adjustment",
            content: "Ticko reserves the right to:",
            list: [
                "Reset portfolios upon suspicion of technical exploitation (bugs) or cheating.",
                "Adjust XP and Levels if obtained through unauthorized methods.",
                "Conduct season-based resets of Paper Trading to maintain competitive spirit."
            ]
        },
        {
            icon: Users,
            title: "8. Rules for User Generated Content",
            content: "As a user, you agree to follow applicable laws and regulations. It is strictly prohibited to:",
            list: [
                "Spread misleading information aimed at influencing stock prices.",
                "Publish material that is offensive, illegal, or constitutes defamation.",
                "Use automated scripts (bots) to extract data or affect platform functionality."
            ],
            footer: "Ticko reserves the right to delete content and permanently suspend accounts violating these rules without warning."
        },
        {
            icon: Lock,
            title: "9. Privacy and Data Protection (GDPR)",
            content: "By using the Service, you agree that we process your personal data in accordance with our Privacy Policy.",
            link: { href: "/privacy", text: "Read our Privacy Policy" }
        },
        {
            icon: Gavel,
            title: "10. Applicable Law and Dispute",
            content: "These terms shall be interpreted in accordance with Swedish law. Disputes shall primarily be resolved through negotiation and secondarily by Swedish general court."
        }
    ];

    return (
        <div className="min-h-screen bg-gradient-to-br from-[#0A0E14] via-[#0D1117] to-[#0A0E14]">
            <div className="max-w-4xl mx-auto px-6 py-16">
                {/* Header */}
                <div className="text-center mb-16">
                    <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 mb-6">
                        <Scale className="w-8 h-8 text-emerald-400" />
                    </div>
                    <h1 className="text-4xl font-bold text-white mb-4">Terms of Service for Ticko</h1>
                    <p className="text-white/40 text-sm">Last updated: January 19, 2026</p>
                </div>

                {/* Intro */}
                <div className="bg-white/[0.02] border border-white/10 rounded-2xl p-6 mb-8">
                    <p className="text-white/70 leading-relaxed">
                        These terms of service (&quot;Terms&quot;) constitute a legally binding agreement between you (&quot;User&quot;) and Ticko regarding the use of the platform tickomarkets.com and associated services. Ticko is an educational platform with simulated trading and not a financial service.
                    </p>
                </div>

                {/* Sections */}
                <div className="space-y-6">
                    {sections.map((section, index) => (
                        <div
                            key={index}
                            className={`bg-white/[0.02] border rounded-2xl p-6 transition-all hover:bg-white/[0.03] ${section.highlight
                                ? 'border-amber-500/30 bg-amber-500/[0.02]'
                                : 'border-white/10'
                                }`}
                        >
                            <div className="flex items-start gap-4">
                                <div className={`flex-shrink-0 w-10 h-10 rounded-xl flex items-center justify-center ${section.highlight
                                    ? 'bg-amber-500/10 border border-amber-500/20'
                                    : 'bg-white/5 border border-white/10'
                                    }`}>
                                    <section.icon className={`w-5 h-5 ${section.highlight ? 'text-amber-400' : 'text-white/40'}`} />
                                </div>
                                <div className="flex-1">
                                    <h2 className={`text-lg font-semibold mb-3 ${section.highlight ? 'text-amber-400' : 'text-white'}`}>
                                        {section.title}
                                        {section.highlight && <span className="ml-2 text-xs bg-amber-500/20 text-amber-400 px-2 py-0.5 rounded-full">Important!</span>}
                                    </h2>

                                    {section.content && (
                                        <p className="text-white/60 leading-relaxed">{section.content}</p>
                                    )}

                                    {section.subsections && (
                                        <div className="space-y-3 mt-3">
                                            {section.subsections.map((sub, subIndex) => (
                                                <div key={subIndex} className="pl-4 border-l-2 border-white/10">
                                                    <span className="text-white/80 font-medium">{sub.label}:</span>{" "}
                                                    <span className="text-white/60">{sub.text}</span>
                                                </div>
                                            ))}
                                        </div>
                                    )}

                                    {section.list && (
                                        <ul className="mt-3 space-y-2">
                                            {section.list.map((item, listIndex) => (
                                                <li key={listIndex} className="flex items-start gap-2 text-white/60">
                                                    <span className="text-red-400 mt-1">•</span>
                                                    <span>{item}</span>
                                                </li>
                                            ))}
                                        </ul>
                                    )}

                                    {section.footer && (
                                        <p className="mt-4 text-white/60 italic">{section.footer}</p>
                                    )}

                                    {section.link && (
                                        <Link
                                            href={section.link.href}
                                            className="inline-flex items-center gap-1 mt-3 text-emerald-400 hover:text-emerald-300 transition-colors text-sm"
                                        >
                                            {section.link.text} →
                                        </Link>
                                    )}
                                </div>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Footer */}
                <div className="mt-12 text-center">
                    <Link
                        href="/"
                        className="text-white/40 hover:text-white/60 transition-colors text-sm"
                    >
                        ← Back to Ticko
                    </Link>
                </div>
            </div>
        </div>
    );
}
